In [29]:
jt -r

NameError: name 'jt' is not defined

In [1]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [2]:
# data analysis and wrangling
import pandas as pd
import numpy as np
import pandas_profiling as pdprof
from dplython import select, DplyFrame, X, arrange, count, sift, head, summarize, group_by, tail, mutate
from math import floor,sqrt
#data modeling
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
import xgboost as xgb

# visualization
import seaborn as sns
import matplotlib.pyplot as plt


C:\Users\Alfonso\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\Alfonso\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\Alfonso\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
training = pd.read_csv("Data/trainingData.csv")
validation = pd.read_csv("Data/validationData.csv")
training.drop_duplicates()
validation.drop_duplicates()

WAP001  WAP002  WAP003  WAP004  WAP005  WAP006  WAP007  WAP008  WAP009  \
0        100     100     100     100     100     100     100     100     100   
1        100     100     100     100     100     100     100     100     100   
2        100     100     100     100     100     100     100     100     100   
3        100     100     100     100     100     100     100     100     100   
4        100     100     100     100     100     100     100     100     100   
5        100     100     100     100     100     100     100     100     100   
6        100     100     100     100     100     100     100     100     100   
7        100     100     100     100     100     100     100     100     100   
8        100     100     100     100     100     100     100     100     100   
9        100     100     100     100     100     100     100     100     100   
10       100     100     100     100     100     100     100     100     100   
11       100     100     100     100     100     100     100     100     100   
12       100     100     100     100     100     100     100     100     100   
13       100     100     100     100     100     100     100     100     100   
14       100     100     100     100     100     100     100     100     100   
15       100     100     100     100     100     100     100     100     100   
16       100     100     100     100     100     100     100     100     100   
17       100     100     100     100     100     100     100     100     100   
18       100     100     100     100     100     100     100     100     100   
19       100     100     100     100     100     100     100     100     100   
20       100     100     100     100     100     100     100     100     100   
21       100     100     100     100     100     100     100     100     100   
22       100     100     100     100     100     100     100     100     100   
23       100     100     100     100     100     100     100     100     100   
24       100     100     100     100     100     100     100     100     100   
25       100     100     100     100     100     100     100     100     100   
26       100     100     100     100     100     100     100     100     100   
27       100     100     100     100     100     100     100     100     100   
28       100     100     100     100     100     100     100     100     100   
29       100     100     100     100     100     100     100     100     -79   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
1081     100     100     100     100     100     100     100     100     100   
1082     100     100     100     100     100     100     100     100     100   
1083     100     100     100     100     100     100     100     100     100   
1084     100     100     100     100     100     100     100     100     100   
1085     100     100     100     100     100     100     100     100     100   
1086     100     100     100     100     100     100     100     100     100   
1087     100     100     100     100     100     100     100     100     100   
1088     100     100     100     100     100     100     100     100     100   
1089     100     100     100     100     100     100     100     100     100   
1090     100     100     100     100     100     100     100     100     100   
1091     100     100     100     100     100     100     100     100     100   
1092     100     100     100     100     100     100     100     100     100   
1093     100     100     100     100     100     100     100     100     100   
1094     100     100     100     100     100     100     100     100     100   
1095     100     100     100     100     100     100     100     100     100   
1096     100     100     100     100     100     100     100     100     100   
1097     100     100     100     100     100     100     100     100     100   
1098     100     100     100     100     100     100     100     100     100   
1099  

In [4]:
nuniqueTrain = training.apply(pd.Series.nunique)
cols_to_drop_train = nuniqueTrain[nuniqueTrain == 1].index
training.drop(columns = cols_to_drop_train)
validation.drop(columns = cols_to_drop_train)
nuniqueValidation = validation.apply(pd.Series.nunique)
cols_to_drop_validation = nuniqueValidation[nuniqueValidation == 1].index
training = training.drop(columns = cols_to_drop_validation).assign(source = "training")
validation = validation.drop(columns = cols_to_drop_validation).assign(source = "validation")
# it would be better to remove the zero variance in each table and then merge the common columns into
# a new data frame to obsesed with the R way of oding things
fullData = pd.concat([training,validation])
fullData =fullData.drop(columns = ['PHONEID','TIMESTAMP'])
fullData[['FLOOR','BUILDINGID']] = fullData[['FLOOR','BUILDINGID']].astype('category')

In [13]:
# pos_max_wap <- apply(full_data %>% select(starts_with('WAP')), 1,
#                      function(x){which.max(x)})
# list_of_WAPS <- sapply(pos_max_wap, function(x){return(names(full_data)[x])})
# full_data<-full_data %>% mutate(highestWAP=list_of_WAPS)
fullData

WAP001  WAP003  WAP004  WAP008  WAP009  WAP010  WAP011  WAP012  WAP013  \
0        100     100     100     100     100     100     100     100     100   
1        100     100     100     100     100     100     100     100     100   
2        100     100     100     -97     100     100     100     100     100   
3        100     100     100     100     100     100     100     100     100   
4        100     100     100     100     100     100     100     100     100   
5        100     100     100     100     100     100     100     100     100   
6        100     100     100     100     100     100     100     100     100   
7        100     100     100     100     100     100     100     100     100   
8        100     100     100     100     100     100     100     100     100   
9        100     100     100     100     100     100     100     100     100   
10       100     100     100     -83     100     100     100     100     100   
11       100     100     100     -90     100     100     100     100     100   
12       100     100     100     100     100     100     100     100     100   
13       100     100     100     100     100     100     100     100     100   
14       100     100     100     100     100     100     100     100     100   
15       100     100     100     100     100     100     100     100     100   
16       100     100     100     100     100     100     100     100     100   
17       100     100     100     100     100     100     100     100     100   
18       100     100     100     100     100     100     100     100     100   
19       100     100     100     100     100     100     100     100     100   
20       100     100     100     100     100     -94     100     100     100   
21       100     100     100     100     100     100     100     100     100   
22       100     100     100     100     100     100     100     100     100   
23       100     100     100     100     100     -95     100     100     100   
24       100     100     100     100     100     100     100     100     100   
25       100     100     100     100     100     100     100     100     100   
26       100     100     100     100     100     100     100     100     100   
27       100     100     100     100     100     100     100     100     100   
28       100     100     100     100     100     100     100     100     100   
29       100     100     100     100     100     100     100     100     100   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
1081     100     100     100     100     100     100     100     100     100   
1082     100     100     100     100     100     100     100     100     100   
1083     100     100     100     100     100     100     100     100     100   
1084     100     100     100     100     100     100     100     100     100   
1085     100     100     100     100     100     100     100     100     100   
1086     100     100     100     100     100     100     100     100     100   
1087     100     100     100     100     100     100     100     100     100   
1088     100     100     100     100     100     100     100     100     100   
1089     100     100     100     100     100     100     100     100     100   
1090     100     100     100     100     100     100     100     100     100   
1091     100     100     100     100     100     100     100     100     100   
1092     100     100     100     100     100     100     100     100     100   
1093     100     100     100     100     100     100     100     100     100   
1094     100     100     100     100     100     100     100     100     100   
1095     100     100     100     100     100     100     100     100     100   
1096     100     100     100     100     100     100     100     100     100   
1097     100     100     100     100     100     100     100     100     100   
1098     100     100     100     100     100     100     100     100     100   
1099  

In [5]:
dataTrain = fullData[fullData.source == 'training'].drop(columns = 'source')
dataValidation = fullData[fullData.source == 'validation'].drop(columns = 'source')

In [ ]:
X_train1 = dataTrain.filter(regex = '^WAP')
y_train.BUILDINGID = dataTrain.BUILDINGID
X_test1 = dataValidation.filter(regex = '^WAP')
y_test.BUILDINGID = dataValidation.BUILDINGID

In [18]:
RandomForestClassifier_ntree1000 = RandomForestClassifier(n_estimators=1000, random_state=123,
                                                          max_depth=32)

In [17]:
xgb_model_class = xgb.XGBClassifier(objective="multi:softprob", random_state = 123, n_estimators=1000,
                                    early_stopping_rounds=10, n_jobs=3)
xgb_model_reg = xgb.XGBRegressor(objective='reg:linear', random_state = 123, n_estimators=2000,
                                    early_stopping_rounds=10, n_jobs=3)

In [ ]:
RandomForest_BUILDING = RandomForestClassifier_ntree1000.fit(X = X_train1,
                                                             y = y_train.BUILDINGID)

In [ ]:
xgb_BUILDING = xgb_model_class.fit(X_train1, y_train.BUILDINGID, early_stopping_rounds=10,
                                   eval_set=[(X_test1, y_test.BUILDINGID)])

In [16]:
predictions_BUILDING = RandomForest_BUILDING.predict(dataValidation.filter(regex = '^WAP'))
predictions_BUILDING_xgb = xgb_BUILDING.predict(dataValidation.filter(regex = '^WAP'))
print(confusion_matrix(predictions_BUILDING,dataValidation.BUILDINGID))
confusion_matrix(predictions_BUILDING_xgb,dataValidation.BUILDINGID)

[[534   1   0]
 [  2 306   0]
 [  0   0 268]]


array([[534,   0,   0],
       [  2, 307,   0],
       [  0,   0, 268]], dtype=int64)

we try to run the random forest and xgb with and without building so we can see if the results improve by adding the building column we will repeat this process in the next predictions, as the results were better for the xgb model we will add these to the test.

In [ ]:
#we got building going so we add a new column to the predictors
X_train2 = X_train1.assign(BUILDINGID = dataTrain.BUILDINGID)
y_train.LONGITUDE = dataTrain.LONGITUDE
X_test2 = X_train1.assign(BUILDINGID = predictions_BUILDING_xgb)
y_test.LONGITUDE = dataValidation.LONGITUDE

In [ ]:
RandomForest_LONG = RandomForestClassifier_ntree1000.fit(X = X_train1,
                                                           y = y_train.LONGITUDE)

In [ ]:
xgb_BUILDING_LONG = xgb_model_reg.fit(X_train1, y_train.BUILDINGID, early_stopping_rounds=10
                                          eval_set=[(X_test1, y_test.LONGITUDE)])

In [ ]:
RandomForest_LONG_wB = RandomForestClassifier_ntree1000.fit(X = X_train2,
                                                           y = y_train.LONGITUDE)

In [ ]:
xgb_BUILDING_LONG_wB = xgb_model_reg.fit(X_train2, y_train.LONGITUDE, early_stopping_rounds=10
                                          eval_set=[(X_test2, y_test.LONGITUDE)])

In [ ]:
predictions_LONGITUDE_rf = RandomForest_LONG.predict(X_test1)
predictions_LONGITUDE_xgb = xgb_BUILDING_LONG.predict(X_test1)
predictions_LONGITUDE_wB_rf = RandomForest_LONG_wB.predict(X_test2)
predictions_LONGITUDE_wB_xgb = xgb_BUILDING_LONG_wB.predict(X_test2)

print("confusion matrix LONGITUDE_rf")
print(confusion_matrix(predictions_LONGITUDE_rf,dataValidation.LONGITUDE))
print("confusion matrix _LONGITUDE_xgb")
print(confusion_matrix(predictions_LONGITUDE_xgb,dataValidation.LONGITUDE))

print("confusion matrix predictions_LONGITUDE_wB_rf")
print(confusion_matrix(predictions_LONGITUDE_wB_rf,dataValidation.LONGITUDE))
print("confusion matrix predictions_LONGITUDE_wB_xgb")
print(confusion_matrix(predictions_LONGITUDE_wB_xgb,dataValidation.LONGITUDE))

In [ ]:
#we got building going so we add a new column to the predictors
X_train2 = X_train1.assign(BUILDINGID = dataTrain.BUILDINGID)
y_train.LATITUDE = dataTrain.LATITUDE
X_test2 = X_train1.assign(BUILDINGID = predictions_BUILDING_xgb)
y_test.LATITUDE = dataValidation.LATITUDE

In [ ]:
RandomForest_LAT = RandomForestClassifier_ntree1000.fit(X = X_train1,
                                                           y = y_train.LATITUDE)

In [ ]:
xgb_BUILDING_LAT = xgb_model_reg.fit(X_train1, y_train.BUILDINGID, early_stopping_rounds=10
                                          eval_set=[(X_test1, y_test.LATITUDE)])

In [ ]:
RandomForest_LAT_wB = RandomForestClassifier_ntree1000.fit(X = X_train2,
                                                           y = y_train.LATITUDE)

In [ ]:
xgb_BUILDING_LAT_wB = xgb_model_reg.fit(X_train2, y_train.LATITUDE, early_stopping_rounds=10
                                          eval_set=[(X_test2, y_test.LATITUDE)])

In [ ]:
predictions_LATITUDE_rf = RandomForest_LAT.predict(X_test1)
predictions_LATITUDE_xgb = xgb_BUILDING_LAT.predict(X_test1)
predictions_LATITUDE_wB_rf = RandomForest_LAT_wB.predict(X_test2)
predictions_LATITUDE_wB_xgb = xgb_BUILDING_LAT_wB.predict(X_test2)

print("confusion matrix LATITUDE_rf")
print(confusion_matrix(predictions_LATITUDE_rf,dataValidation.LATITUDE))
print("confusion matrix _LATITUDE_xgb")
print(confusion_matrix(predictions_LATITUDE_xgb,dataValidation.LATITUDE))

print("confusion matrix predictions_LATITUDE_wB_rf")
print(confusion_matrix(predictions_LATITUDE_wB_rf,dataValidation.LATITUDE))
print("confusion matrix predictions_LATITUDE_wB_xgb")
print(confusion_matrix(predictions_LATITUDE_wB_xgb,dataValidation.LATITUDE))